"""create_planner_items

Revision ID: 6975030d988a
Revises: 5febd958269d
Create Date: 2026-08-20 22:55:16.956871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6975030d988a'
down_revision: Union[str, Sequence[str], None] = '5febd958269d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planner_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planner_items_date'), 'planner_items', ['date'], unique=False)
    op.create_index(op.f('ix_planner_items_id'), 'planner_items', ['id'], unique=False)
    op.create_index(op.f('ix_planner_items_status'), 'planner_items', ['status'], unique=False)
    op.create_index(op.f('ix_planner_items_user_id'), 'planner_items', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_planner_items_user_id'), table_name='planner_items')
    op.drop_index(op.f('ix_planner_items_status'), table_name='planner_items')
    op.drop_index(op.f('ix_planner_items_id'), table_name='planner_items')
    op.drop_index(op.f('ix_planner_items_date'), table_name='planner_items')
    op.drop_table('planner_items')
    # ### end Alembic commands ###
